# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Journal < Formula
  desc "Simple blog available as an api, written in go with accompanying tests and doc"
  homepage "https://github.com/jamiefdhurst/journal"
  url "https://github.com/jamiefdhurst/journal/archive/refs/tags/1.0.0.tar.gz"
  sha256 "ec97e1820102beea9b59557c7d403e1f06c17c8ac51b0ae5778f06c2eee9ce54"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/jamiefdhurst/journal/releases/download/1.0.0/journal-1.0.0-darwin-amd64.tar.gz"
      sha256 "6a39d2e31b9f84b94ee7512773e484e51b491b361814d9b27c044ddf42a6d6d1"
    end

    on_arm do
      url "https://github.com/jamiefdhurst/journal/releases/download/1.0.0/journal-1.0.0-darwin-arm64.tar.gz"
      sha256 "1576330d3c69474dee05062078db8dd43457f142597de27f6a42cdae41271f20"
    end
  end

  def install
    libexec.install "journal" => "journal-bin"
    libexec.install "web"
    (bin/"journal").write "#!/bin/sh\ncd \"#{libexec}\"\nexec \"#{libexec}/journal-bin\" \"$@\"\n"
  end

  test do
    output = shell_output("#{bin}/journal 2>&1", 1)
    assert_match "Journal v#{version}", output
  end
end
