# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Journal < Formula
  desc "Simple blog available as an api, written in go with accompanying tests and doc"
  homepage "https://github.com/jamiefdhurst/journal"
  url "https://github.com/jamiefdhurst/journal/archive/refs/tags/1.0.2.tar.gz"
  sha256 "13e075fe5f25f36a5933370d37e8e2c90bd041b9d56fc4d26d58379b6ca95ab1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/jamiefdhurst/journal/releases/download/1.0.2/journal-1.0.2-darwin-amd64.tar.gz"
      sha256 "332e3803a5cbdc079d7379c72fc35e68858e42b53ab4390276924ce4255c0738"
    end

    on_arm do
      url "https://github.com/jamiefdhurst/journal/releases/download/1.0.2/journal-1.0.2-darwin-arm64.tar.gz"
      sha256 "78bfa9ceb4d02dc3d21e61cb20eba1f6c391bf5f1b74163f6b50f61b73b0c2af"
    end
  end

  def install
    libexec.install "journal" => "journal-bin"
    libexec.install "web"
    (bin/"journal").write "#!/bin/sh\ncd \"#{libexec}\"\nexec \"#{libexec}/journal-bin\" \"$@\"\n"
  end

  test do
    output = shell_output("#{bin}/journal 2>&1", 1)
    assert_match "Journal v#{version}", output
  end
end
