# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Journal < Formula
  desc "Simple blog available as an api, written in go with accompanying tests and doc"
  homepage "https://github.com/jamiefdhurst/journal"
  url "https://github.com/jamiefdhurst/journal/archive/refs/tags/1.0.1.tar.gz"
  sha256 "6e9f768d9251795f6b027d26a545cc26d2159b70581dc5145b74b4b9ceefa060"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/jamiefdhurst/journal/releases/download/1.0.1/journal-1.0.1-darwin-amd64.tar.gz"
      sha256 "99f6756170299b5636566d4f426d713dcd1ecea834bbba74b70d28e02d300713"
    end

    on_arm do
      url "https://github.com/jamiefdhurst/journal/releases/download/1.0.1/journal-1.0.1-darwin-arm64.tar.gz"
      sha256 "09f0721c6782ae5f9ad8e951965c31e1d3131e4e842f3156c7aa3953fe13b940"
    end
  end

  def install
    libexec.install "journal" => "journal-bin"
    libexec.install "web"
    (bin/"journal").write "#!/bin/sh\ncd \"#{libexec}\"\nexec \"#{libexec}/journal-bin\" \"$@\"\n"
  end

  test do
    output = shell_output("#{bin}/journal 2>&1", 1)
    assert_match "Journal v#{version}", output
  end
end
